import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by `flutterfire configure`.
///
/// Replace this template by running:
/// `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return null;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS Firebase options are not configured. '
          'Run flutterfire configure to generate firebase_options.dart.',
        );
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'This platform is not configured for Firebase in this app.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJRa_5lnLx9LIXdQEqIjWcRowdUcr7nyM',
    appId: '1:633846456010:android:63535f5c5aa7447c461e33',
    messagingSenderId: '633846456010',
    projectId: 'winter-brand-405107',
    databaseURL: 'https://winter-brand-405107-default-rtdb.firebaseio.com',
    storageBucket: 'winter-brand-405107.firebasestorage.app',
  );
}
